import { NextFunction, Request, Response } from 'express';
import z, { ZodError } from 'zod';
import config from '../config/config';
import ServerResponse from '../helpers/responses/custom-response';

/**
 * Handles errors generated by Zod schema validation.
 *
 * @param req - The request object.
 * @param res - The response object.
 * @param zodErr - The Zod error object.
 * @returns The response object with error details.
 */
const zodErrorHandler = (req: Request, res: Response, zodErr: ZodError): Response => {
  // Extract and format errors from the Zod error object
  const errors = zodErr.issues.map((err) => ({
    field: err?.path?.join(', '),
    message: err?.message,
  }));

  // Log errors in any mode except production
  if (config.NODE_ENV !== 'production') {
    console.log(errors);
  }

  // Send error response using the global response helper
  return ServerResponse(res, false, 400, 'Validation error', null, errors);
};

/**
 * Helper (assuming you have something like this)
 */
function validate<T extends z.ZodTypeAny>(schema: T) {
  return (req: Request, res: Response, next: NextFunction) => {
    const result = schema.safeParse(req.body);

    if (!result.success) {
      return zodErrorHandler(req, res, result.error);
    }

    // Optional: attach validated & typed data
    req.body = result.data;

    next();
  };
}

export { validate, zodErrorHandler };
