import { AppSidebar } from "@/components/app-sidebar";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='flex flex-col min-h-screen relative'>
          {/* Sticky Header */}
          <header className='bg-primary text-primary-foreground px-20 py-10.75 flex items-center justify-between sticky top-0 z-30'>
            <div className='flex items-center gap-3'>
              <Image src='/logo.png' alt='OCMP Logo' width={150} height={37} />
            </div>
            <div className='flex items-center gap-3'>
              <span className='text-base'>Hello, Admin</span>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Avatar className='h-14.75 w-14.75 cursor-pointer'>
                    <AvatarImage
                      src='/images/user-avatar.png'
                      alt='Admin Avatar'
                    />
                    <AvatarFallback className='text-foreground font-black'>
                      AD
                    </AvatarFallback>
                  </Avatar>
                </DropdownMenuTrigger>
                <DropdownMenuContent align='end'>
                  <DropdownMenuItem className='hover:bg-primary-bg! cursor-pointer hover:text-white'>
                    Profile
                  </DropdownMenuItem>
                  <DropdownMenuItem className='hover:bg-primary-bg! cursor-pointer hover:text-white'>
                    Settings
                  </DropdownMenuItem>
                  <DropdownMenuItem className='hover:bg-destructive! cursor-pointer hover:text-white'>
                    Logout
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </header>
          {/* Sticky Sidebar and scrollable main content */}
          <div className='flex flex-1 min-h-0'>
            <SidebarProvider defaultOpen={defaultOpen}>
              <div className='sticky left-0 top-0 h-[70vh] z-50'>
                <AppSidebar />
              </div>
              <main className='flex-1 h-full px-8 py-10 overflow-y-auto min-h-0'>
                {children}
              </main>
            </SidebarProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
